### ISSUE TITLE
No cambia el order_status_id cuando se ejecuta addRecordHistory

### ISSUE THREAD

**Issue by diernan** [TodoPago/Plugin-OpenCart3#1]
Anteriormente dentro de ControllerExtensionPaymentTodopago->callGAA se llamaba al método ModelCheckoutOrder->addOrderHistory el cual recibía como parámetros el order_id y el order_status_id.

`#$this->model_checkout_order->addOrderHistory($this->order_id, $this->config->get('payment_todopago_order_status_id_aprov'), "TODO PAGO: " . $rta_second_step['StatusMessage']);`

Dicho método fue reemplazado por ControllerExtensionPaymentTodopago->addRecordHistoy que recibe como parámetro statusMessage.

`$this->addRecordHistory('TODO PAGO: ' . $rta_second_step['StatusMessage']);`

Dentro del método ControllerExtensionPaymentTodopago->addRecordHistory se llama a ModelCheckoutOrder->addOrderHistory pero el order_status_id es siempre el mismo ya que se busca en la tabla oc_setting el valor de payment_todopago_order_status_id_pro, valor que debería variar según haya sido el resultado de la operación. Por ejemplo payment_todopago_order_status_id_aprov para las operaciones aprobadas.

`$this->model_checkout_order->addOrderHistory($this->order_id, $this->config->get('payment_todopago_order_status_id_pro'), "TODO PAGO: " . $statusMessage);`

**Comment by drarko** [comment]
Estimado,
Acabamos de subir una version que corrige este inconveniente. Por favor, actualizar y probar nuevamente
Reabrir en caso de ser necesario.
Gracias
